### ISSUE TITLE
How to use useWatch when args are changing

### ISSUE THREAD

**Issue by DemidenkoAndrey** [lostpebble/pullstate#76] opened 2020-11-30 10:20 UTC
I had an issue that useWatch depends on args.
I want to use useWatch with some args, that will change depending on user's actions.
How should I specify useWatch to be able to track finished?

**Comment by lostpebble** [comment] 2020-11-30 10:29
Can you please provide a small example of what you are trying to do? You can just give the general idea.

`useWatch` accepts arguments for the action, so I'm unsure what the problem is.

**Comment by DemidenkoAndrey** [comment] 2020-11-30 10:37
I'm trying to fetch list of items with pagination, first load runs on button click.


`
[finished] = loadItems.useWatch();
`

On a button click I call 
`loadItems.run({ page: 1 });`

And then when user changes page
`loadItems.run({ page: variable_for_page });`

**Comment by DemidenkoAndrey** [comment] 2020-11-30 10:40
In previous example finished is always false.

**Comment by DemidenkoAndrey** [comment] 2020-11-30 11:00
Looked up into source code: I found that I can achieve my desired result if I set custom key:
`
[, finished] = loadItems.useWatch(null, { key: 'someKey' );
`

On a button click I call 
`loadItems.run({ page: 1 }, {key: 'someKey'});`

And then when user changes page
`loadItems.run({ page: variable_for_page }, {key: 'someKey'});`

Is this the only option to achieve this if so can you add this example into docs. Because there is not option 'key' there.

**Comment by lostpebble** [comment] 2020-11-30 11:07
Okay, I see.

Generally what you do in this situation, is you provide the arguments from a previous state which you can update. For example:

```ts
const [loadItemArgs, setLoadItemArgs] = useState({ page: 1 });
[, finished] = loadItems.useWatch(loadItemArgs);

// ...later in button click

setLoadItemArgs({ page: variable_for_page });
```

But there is a new way to use Async Actions which I need to create the documentation for which may suit your case better:

```ts
const loadItemsAction = loadItems.useDefer();

// This will only execute and return components to render if the action is complete and successful
loadItemsAction.renderPayload(({ items }) => {
  return <List items={items} />
})

// Or, you can use similar (and some extra useful) properties as useWatch
loadItemsAction.isFinished
loadItemsAction.isSuccessful

// ...later in button click
loadItemsAction.execute({ page: 1 });
```

`useDefer()` was created for situations like yours, where you want to "defer" an action to run later, according to user actions- so you don't have to manage the internal state of the arguments yourself.

Hope that helps, let me know if it doesn't work out for your situation somehow.

**Comment by DemidenkoAndrey** [comment] 2020-11-30 11:46
@lostpebble Thanks for your answer and such quick reply. Should I close the issue?

**Comment by lostpebble** [comment] 2020-11-30 11:56
Sure, I think we can close it. The documentation needs to be updated, but that is being tracked in a different issue already.

Glad things are resolved on your side!

**Closed by lostpebble** 2020-11-30 11:56 UTC

**Comment by DemidenkoAndrey** [comment] 2020-11-30 14:58
@lostpebble Found, that useBeckon missed 'key' option.

**Comment by lostpebble** [comment] 2020-11-30 15:49
@DemidenkoAndrey  - I'm pretty sure it does, just checked the types.

But as I mentioned before - I think you want to use `useDefer()` it does all the "key" stuff for you.

**Comment by DemidenkoAndrey** [comment] 2020-11-30 16:11
https://github.com/lostpebble/pullstate/blob/dc5483148295cd1e789f2d45a6a4ee3074b54bd1/src/async.ts#L726

It doesn't forward 'key' option to useWatch

I understand about useDefer, just looked at useBeckon source code.

**Comment by lostpebble** [comment] 2020-11-30 16:44
Ah, good catch! I'll push an update now for that.

**Comment by lostpebble** [comment] 2020-11-30 16:58
Latest version should work with `useBeckon` and keys.

**Comment by DemidenkoAndrey** [comment] 2020-11-30 17:06
@lostpebble Thanks.
