### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by richardvuu** [lostpebble/pullstate#25] opened 2020-01-28 21:51 UTC
I'm getting a few warnings of:

```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.```

Possibly this is related to the dynamic getSubState changes from the prior issue?

Altering this line: https://github.com/lostpebble/pullstate/blob/master/src/useStoreStateOpt.ts#L67 to return the `removeListener` thing as a callback instead of executing it on-mount seems to resolve it, but I have no idea if that's a valid solution.

**Comment by lostpebble** [comment] 2020-01-29 06:51
Are you using `useStoreStateOpt` ? Or `useStoreState` ?

`useStoreStateOpt` hasn't got any of the changes I put in for useStoreState- its a completely different way of tracking changes, potentially more performant in certain situations, but it hasn't been fully fleshed out yet.

In any case, If you look at that code you referenced, the entire thing is a returned callback - the `useEffect` doesn't actually run anything, but returns the cleanup function.

I assume you actually meant `useStoreState`. How are you using `useStoreState` ? If you are creating dynamic sub-state selectors, you need to ensure you are always passing in an array of dependents as the last argument:

```
useStoreState(store, (s) => s[type], [type]);
```

If you don't, you will get those no-op errors.

**Comment by lostpebble** [comment] 2020-02-03 13:44
@richardvuu are you still running into these issues?

If so I'll look into it soon. I haven't made use of the dynamic state selection in my apps yet, so can't really verify it yet. From what I can see, things should be getting cleaned up correctly.

**Comment by richardvuu** [comment] 2020-02-03 14:54
Hi Paul,

Sorry, I had a deadline last week and emails got missed.

I am using `useStoreState`, not `''Opt`, I was just mucking around with the source to make things work. As far as I can tell from the code it was not returning the unbound function *but* it hasn't been for at least 12 months so I'm not sure *why* that fixed anything.

I'm only using the dynamic substate in one place I think, and this error is appearing from other places.

**Comment by lostpebble** [comment] 2020-02-03 15:20
@richardvuu no worries!

Interesting... If you are getting this in places where you are not using dynamic state and it hasn't been happening before- is there is a chance that its not related to Pullstate? Or is the error showing that its coming from inside Pullstate's code?

I've run into that error in my projects quite a bit before. Basically boils down to trying to update state to a component which has already been removed from the React tree.

I haven't run into any of those errors and I'm using Pullstate quite extensively in my projects- so that's why I thought it might be related to the dynamic way of using it only.

I'm going to add a little bit of code that might fix the issue for you- basically do a double check to make sure that the component hasn't been unmounted yet before running the state update. Right now, if the equality check between the previous and current states takes too long, then it might run the update on a component that might have been unmounted already.

**Comment by lostpebble** [comment] 2020-02-03 17:55
@richardvuu Just released a new version - check it out and let me know if the issue still persists.

**Comment by lostpebble** [comment] 2020-02-06 14:10
Since I haven't been able to reproduce this myself, and I've released a very conservative change that double checks whether a component is still mounted or not before triggering a state update, I'm gonna close this for now.

Feel free to re-open if its still a problem though!

**Closed by lostpebble** 2020-02-06 14:10 UTC
